First Commit
fortinet-fortisoar/widget-playbook-execution-wizard pull request #2
Opened 2024-01-04 06:29 UTC by cs-sujeet-ahirrao

First Commit

2024-01-08 11:00 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +        if (response['hydra:member'].length > 0) {
response['hydra:member'] add check

2024-01-08 11:00 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +        if (response['hydra:member'].length > 0) {
response['hydra:member'] add check

2024-01-08 11:06 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +            "value": $scope.config.metadata.getSelectedRows[0].new_branch + '-' + $scope.config.metadata.getSelectedRows[0].summary,
preferably put this in a variable above queryBody and add here.
var _xyz = $scope.config.metadata.getSelectedRows[0].new_branch + '-' + $scope.config.metadata.getSelectedRows[0].summary;

value: _xyz

2024-01-08 11:07 UTC, cs-pranali-chavan requested changes
comments added. rest code is appropriate

2024-01-10 05:59 UTC, cs-pranali-chavan approved these changes
changes are appropriate

2024-01-24 05:43 UTC, cs-suyog-jinturkar approved these changes

2024-01-24 05:43 UTC, merged