Enhancements
fortinet-fortisoar/widget-playbook-execution-wizard pull request #3
Opened 2024-01-25 06:10 UTC by cs-sujeet-ahirrao

1. If playbook is active or awaiting then don't execute playbook again
2. Handled Playbook failed condition
3. Get playbook and playbook record details from $scope.payload rather than $scope.config
4.  Handle console Error: ngRepeat:dupes Duplicate Key in Repeater in [playbookPendingDecision.directive.js and playbookPendingDecision.html]

2024-01-25 08:50 UTC, cs-pranali-chavan commented on widget/view.controller.js
>            $scope.dummyRecordIRI = response['hydra:member'][0]['@id'].replace('/api/3/', '');
hydra member check has been removed

2024-01-25 08:57 UTC, cs-pranali-chavan requested changes
Check comments. Rest code is appropriate

2024-01-25 08:57 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +        if (response['hydra:member'].length > 0) {
hydra member check has been removed

2024-01-25 08:57 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +          body: "You dont have permission to execute the playbooks"
playbook will be singular if this code is for selected playbook

2024-01-25 09:45 UTC, cs-pranali-chavan approved these changes
Looks appropriate

2024-01-25 09:49 UTC, cs-pranali-chavan requested changes
Kindly add copyright 
  MIT License
  Copyright (c) 2024 Fortinet Inc
in all html, js and css files

2024-01-29 11:58 UTC, cs-pranali-chavan approved these changes
Looks good. Code is appropriate

2024-01-29 12:01 UTC, cs-suyog-jinturkar approved these changes

2024-01-29 12:01 UTC, merged